name: log_message
description: Global logging system
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  mutation_test: ^1.3.1
  test: ^1.21.5
  very_good_analysis: ^3.0.1
dependencies:
  clock: ^1.1.1
