name: logger
description: Global logging system
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: 3.0.1
