name: log_message
description: Global logging system
version: 0.2.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypt:
    git:
      url: https://github.com/Marc-R2/encrypt_dart.git
      ref: 8cf39659
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  clock: ^1.1.1
  freezed: any
  json_serializable: any
  mutation_test: ^1.3.2
  test: ^1.22.2
  very_good_analysis: ^3.1.0
